### ISSUE TITLE
The Dex Path String Must Not Be Empty

### ISSUE THREAD

**Issue by darmie** [lukeFalsina/Grab-n-Run#5]
I am getting this error while trying to load a class 
```
java.lang.IllegalArgumentException: The dex path string must not be empty
                                                                             at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
                                                                             at it.necst.grabnrun.DexPathStringProcessor.<init>(DexPathStringProcessor.java:27)
                                                                             at it.necst.grabnrun.SecureDexClassLoader.generatePackageNameToContainerPathMap(SecureDexClassLoader.java:206)
                                                                             at it.necst.grabnrun.SecureDexClassLoader.<init>(SecureDexClassLoader.java:185)
                                                                             at it.necst.grabnrun.SecureLoaderFactory.createDexClassLoader(SecureLoaderFactory.java:292)
                                                                             at it.necst.grabnrun.SecureLoaderFactory.createDexClassLoader(SecureLoaderFactory.java:204)
                                                                             at com.adroyte.stellar.Stellar.loadClass(Stellar.java:107)
                                                                             at com.adroyte.stellar.Stellar.execute(Stellar.java:58)
```

Code is here:
```java
	private boolean loadClass(JSONArray args, CallbackContext callbackContext) throws JSONException {
		String classPath = args.getString(0);
		Log.d("Stellar: Class Path", classPath);
		Log.d("Stellar: Apk Path", jarContainerPath);
		if(initialized){
			try{
				SecureLoaderFactory mSecureLoaderFactory = new SecureLoaderFactory(this.cordova.getActivity());
				mSecureDexClassLoader = mSecureLoaderFactory.createDexClassLoader(jarContainerPath, null, this.getClass().getClassLoader(), packageNamesToCertMap);
				loadedClass = mSecureDexClassLoader.loadClass(classPath);
				// Check whether the signature verification process succeeds
				if (loadedClass != null) {
					String type = classPath;
					// Class loading was successful and performed in a safe way.
					classInstance = loadedClass.newInstance();
					classLoaded = true;
					return classLoaded;
				}else{
					callbackContext.error("Class was not loaded!");
					return false;
				}
			} catch (ClassNotFoundException e) {
					// This exception will be raised when the container of the target class
					// is genuine but this class file is missing..
					callbackContext.error("Class not found!");
					e.printStackTrace();
			} catch (InstantiationException e) {
					e.printStackTrace();
					callbackContext.error("Library is not initialized!");
			} catch (IllegalAccessException e) {
					e.printStackTrace();
					callbackContext.error("Library is not initialized!");
			}
		}else {
            callbackContext.error("Library is not initialized!");
			return false;			
		}

		return false;
	}
```

**Comment by lukeFalsina** [comment]
Hello @darmie,

Please double check the content of your variable ``jarContainerPath`` as most likely this is empty and that is why you see that precondition failing when you create a ``SecureDexClassLoader`` object.

The reason for that check for being there is you can not expect to be able to load any class dynamically if you do not provide the ``DexClassLoader`` class with the list of APK and/or JAR in which the class you want to load should be found.

Let me know whether this helps.

**Comment by darmie** [comment]
Thanks for the timely response @lukeFalsina 

The `jarContainerPath` is not empty, it contains the link to the apk I want to load `https://dl.dropboxusercontent.com/content_link/BGg2XMDbx4UlTMWfYJQ6ImWHr6MSJfDVLukIc2LGoOPm8xMOCmVGXnpKB1DHdiaq/file`

I got the following logs which points that the file was downloaded and mounted
```
com.XXXX.streetvendor D/SecureLoaderFactory: Download Resource Dir has been mounted at: /data/data/com.XXXX.streetvendor/app_imported_cont
com.XXXX.streetvendor D/SecureLoaderFactory: Dex Output Dir has been mounted at: /data/data/com.XXXX.streetvendor/app_dex_classes
```

**Comment by darmie** [comment]
Resolved. issue was with the new Dropbox. The URL doesn't seem to work with Grab'n'Run.  

Before I close this issue, I have a question. Is it possible for container APK to access it's own Asset files?

**Comment by lukeFalsina** [comment]
I see. Thanks for closing the issues.

Regarding your question I believe you will not be able to access assets as the ``DexClassLoader`` API on which Grab'n Run is build on is, to the best of my knowledge, only able to load compiled Dex classes. But of course you are free to try it out and prove me wrong :)

**Comment by darmie** [comment]
Yeah, I figured that out. I am going to decompress the apk and save the
assets file somewhere.

Thanks.
